# Generated by Django 4.2.16 on 2024-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.BigIntegerField()),
                ('album', models.TextField()),
                ('number', models.TextField()),
                ('series', models.TextField()),
                ('writer', models.TextField()),
                ('illustrator', models.TextField()),
                ('colorist', models.TextField()),
                ('publisher', models.TextField()),
                ('publication_date', models.TextField()),
                ('edition', models.TextField()),
                ('number_of_pages', models.TextField()),
                ('rating', models.TextField()),
                ('purchase_price', models.TextField()),
                ('year_of_purchase', models.TextField()),
                ('place_of_purchase', models.TextField()),
                ('deluxe_edition', models.TextField()),
                ('signed_copy', models.TextField()),
                ('ex_libris', models.TextField()),
                ('synopsis', models.TextField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'BD',
            },
        ),
    ]
