# Generated by Django 4.2.16 on 2024-12-15 14:41

from django.db import migrations

from main.core.application.usecases.update_database.update_database_service import UpdateDatabaseService
from main.core.infrastructure.persistence.database.database_adapter import DatabaseAdapter
from main.core.infrastructure.persistence.sheet.sheet_adapter import SheetAdapter


def insert_initial_data(apps, schema_editor) -> None:
    sheet_repository = SheetAdapter()
    database_repository = DatabaseAdapter()
    service = UpdateDatabaseService(sheet_repository, database_repository)
    service.main()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
