# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations

from main.core.domain.model.app_user import AppUser
from main.core.domain.model.collection import Collection
from main.core.infrastructure.persistence.database.table_collection_adapter import TableCollectionAdapter
from main.core.infrastructure.persistence.database.table_user_adapter import TableUserAdapter

try:
    from main.core.application.create_users import create_local_users
except ImportError:
    def create_local_users():
        pass


def insert_initial_data(apps, schema_editor) -> None:
    user_repository = TableUserAdapter()
    collection_repository = TableCollectionAdapter()

    admin_internal = AppUser(username="admin", password="admin", first_name="Admin",
                             email="admin@email.com")
    admin = user_repository.create(admin_internal)
    collection_internal = Collection(title="Collection de Test", accounts=[admin])
    collection_repository.create(collection_internal)
    create_local_users()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
