# Generated by Django 5.2.2 on 2025-06-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_insert_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='current_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_users', to='main.collection'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
