# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations

from main.core.domain.model.profile import Profile
from main.core.domain.model.profile_type import ProfileType

try:
    from main.core.application.create_users import create_local_users
except ImportError:
    def create_local_users(profiles: dict[ProfileType, Profile]):
        pass # Si aucun fichier d'initialisation est trouvé


def insert_initial_data(apps, schema_editor) -> None:
    Profile = apps.get_model('main', 'Profile')
    Collection = apps.get_model('main', 'Collection')
    AppUser = apps.get_model('main', 'AppUser')

    # Création des profils
    profile_bd = Profile.objects.create(name="BD")
    Profile.objects.create(name="BOOK")

    # Création de l'admin
    admin = AppUser.objects.create(
        username="admin",
        password="admin",
        first_name="Admin",
        email="admin@email.com"
    )

    # Création de la collection
    collection = Collection.objects.create(
        title="Collection de Test",
        token="XIWzYF4RFb77U4obBcfBF2UfVFE0hK2Aq43UV9e8d1EpLye7wXxGPHFwCVmMExb8",
        doc_name="1z4iFF1ROr_sXZkkFJS12kKk7ndUaA9fNconarZIAIxo",
        sheet_name="Test",
        profile=profile_bd
    )

    # Ajout de la relation ManyToMany
    collection.accounts.add(admin)

    admin.current_collection = collection
    admin.save()

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
