# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations


def insert_initial_data(apps, schema_editor) -> None:
    profile_table = apps.get_model('main', 'Profile')
    collection_table = apps.get_model('main', 'Collection')
    app_user_table = apps.get_model('main', 'AppUser')

    # --- Profils ---
    profile_bd, _ = profile_table.objects.get_or_create(name="BD")
    profile_table.objects.get_or_create(name="BOOK")

    # --- Admin ---
    admin, _ = app_user_table.objects.get_or_create(
        username="admin",
        defaults={
            "first_name": "Admin",
            "email": "admin@email.com",
            "password": "admin",
        }
    )

    # --- Collection de test ---
    collection, _ = collection_table.objects.get_or_create(
        title="Collection de Test",
        defaults={
            "token": "XIWzYF4RFb77U4obBcfBF2UfVFE0hK2Aq43UV9e8d1EpLye7wXxGPHFwCVmMExb8",
            "doc_id": "1z4iFF1ROr_sXZkkFJS12kKk7ndUaA9fNconarZIAIxo",
            "sheet_name": "Test",
            "profile": profile_bd,
        }
    )

    # Ajout admin → collection
    collection.accounts.add(admin)

    # Définir la collection courante
    admin.current_collection = collection
    admin.save()


def remove_initial_data(apps, schema_editor) -> None:
    profile_table = apps.get_model('main', 'Profile')
    collection_table = apps.get_model('main', 'Collection')
    app_user_table = apps.get_model('main', 'AppUser')

    # ⚠️ On ne supprime que ce que l’on a créé
    collection_table.objects.filter(title="Collection de Test").delete()
    profile_table.objects.filter(name__in=["BD", "BOOK"]).delete()
    app_user_table.objects.filter(username="admin").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data, remove_initial_data)
    ]
