# Generated by Django 5.2.2 on 2025-08-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_appuser_current_collection_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bd_rows', to='main.collection'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.BigIntegerField()),
                ('title', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('translator', models.TextField()),
                ('publisher', models.TextField()),
                ('collection_book', models.TextField()),
                ('publication_date', models.DateField(null=True)),
                ('edition', models.TextField()),
                ('number_of_pages', models.IntegerField(null=True)),
                ('literary_genre', models.TextField()),
                ('style', models.TextField()),
                ('origin_language', models.TextField()),
                ('purchase_price', models.FloatField(null=True)),
                ('year_of_purchase', models.IntegerField(null=True)),
                ('place_of_purchase', models.TextField()),
                ('localisation', models.TextField()),
                ('synopsis', models.TextField()),
                ('image', models.URLField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rows', to='main.collection')),
            ],
        ),
    ]
