# Generated by Django 5.2.2 on 2025-08-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bd_collection_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='doc_name',
            new_name='doc_id',
        ),
    ]
